### PR TITLE
Multi-version support, firmware updates

### PR DESCRIPTION
**Pull request by phlash**
Hi Alex,

These changes permit one version of fcdctl to operate with different versions of FCD hardware, and to perform firmware updates, verification and extraction.

your thoughts welcome :)

Phil.

### CODE REVIEW

**Comment by csete** [comment]
Hi Phil,

Thanks for the patch. Looks interesting and I want to merge it. However, I noticed that if I dump the firmware from my FCD Pro it will read 64512 bytes while the export18j.pro.bin file is 66048. Any idea?
The dump from Pro+ seems to read the correct size.

**Comment by phlash** [comment]
Possibly the memory addresses reported by an FCD Pro limit the read out loop, does the dump verify (or load back in and boot?). The firmware files provided by Howard appear to be page aligned memory dumps with some excess at either end so size may not matter much. Unfortunately I don't have my FCD Pro to hand. I'll borrow one and check myself later this week..

**Comment by phlash** [comment]
Hi Alex,

I've been able to test with an FCD Pro (V1.0), and all works as expected - the file sizes are different because when I write a dump file, I pad from address 0 to the start address, then write blocks until I reach the end address (as reported by the device). Howard takes memory images from the development system via his PIC programmer, so his files are multiples of the page size, extending beyond the end address of the device.

I have been able to dump existing firmware, verify against stock firmware (both on device and comparing file contents between start/end addresses), reprogram using both stock and dump files and verify that the device boots in all cases.

**Comment by csete** [comment]
On Wed, Jul 9, 2014 at 10:31 PM, Phil Ashby notifications@github.com
wrote:

> Hi Alex,
> 
> I've been able to test with an FCD Pro (V1.0), and all works as expected -
> the file sizes are different because when I write a dump file, I pad from
> address 0 to the start address, then write blocks until I reach the end
> address (as reported by the device). Howard takes memory images from the
> development system via his PIC programmer, so his files are multiples of
> the page size, extending beyond the end address of the device.
> 
> I have been able to dump existing firmware, verify against stock firmware
> (both on device and comparing file contents between start/end addresses),
> reprogram using both stock and dump files and verify that the device boots
> in all cases.

Hi Phil,

Thanks for the info. I'll merge the changes as soon as I get some time
(hopefully during the coming weekend).

Alex

**Pull request closed without merging**
